import type {Metadata} from "next";

export function Seo(pageTitle: string): Metadata {
    return {
        title: `Coders Monkeys | ${pageTitle}`,
        description: "Generated by create next app",
    }
}